-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity navdepp is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2d_22_input_input_array_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    conv2d_22_input_input_array_ce0 : OUT STD_LOGIC;
    conv2d_22_input_input_array_we0 : OUT STD_LOGIC;
    conv2d_22_input_input_array_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    conv2d_22_input_input_array_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2d_22_input_input_array_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    conv2d_22_input_input_array_ce1 : OUT STD_LOGIC;
    conv2d_22_input_input_array_we1 : OUT STD_LOGIC;
    conv2d_22_input_input_array_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    conv2d_22_input_input_array_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2d_22_input_input_ndim : IN STD_LOGIC_VECTOR (63 downto 0);
    conv2d_22_input_input_numel : IN STD_LOGIC_VECTOR (63 downto 0);
    conv2d_22_input_input_shape_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    conv2d_22_input_input_shape_ce0 : OUT STD_LOGIC;
    conv2d_22_input_input_shape_we0 : OUT STD_LOGIC;
    conv2d_22_input_input_shape_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    conv2d_22_input_input_shape_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    conv2d_22_input_input_shape_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    conv2d_22_input_input_shape_ce1 : OUT STD_LOGIC;
    conv2d_22_input_input_shape_we1 : OUT STD_LOGIC;
    conv2d_22_input_input_shape_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    conv2d_22_input_input_shape_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_array_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    dense_23_output_array_ce0 : OUT STD_LOGIC;
    dense_23_output_array_we0 : OUT STD_LOGIC;
    dense_23_output_array_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_23_output_array_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    dense_23_output_array_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    dense_23_output_array_ce1 : OUT STD_LOGIC;
    dense_23_output_array_we1 : OUT STD_LOGIC;
    dense_23_output_array_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_23_output_array_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    dense_23_output_ndim : IN STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_numel : IN STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_shape_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    dense_23_output_shape_ce0 : OUT STD_LOGIC;
    dense_23_output_shape_we0 : OUT STD_LOGIC;
    dense_23_output_shape_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_shape_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_shape_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    dense_23_output_shape_ce1 : OUT STD_LOGIC;
    dense_23_output_shape_we1 : OUT STD_LOGIC;
    dense_23_output_shape_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    dense_23_output_shape_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of navdepp is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "navdepp,hls_ip_2018_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=15,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_done <= ap_const_logic_0;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_0;
    conv2d_22_input_input_array_address0 <= ap_const_lv14_0;
    conv2d_22_input_input_array_address1 <= ap_const_lv14_0;
    conv2d_22_input_input_array_ce0 <= ap_const_logic_0;
    conv2d_22_input_input_array_ce1 <= ap_const_logic_0;
    conv2d_22_input_input_array_d0 <= ap_const_lv32_0;
    conv2d_22_input_input_array_d1 <= ap_const_lv32_0;
    conv2d_22_input_input_array_we0 <= ap_const_logic_0;
    conv2d_22_input_input_array_we1 <= ap_const_logic_0;
    conv2d_22_input_input_shape_address0 <= ap_const_lv3_0;
    conv2d_22_input_input_shape_address1 <= ap_const_lv3_0;
    conv2d_22_input_input_shape_ce0 <= ap_const_logic_0;
    conv2d_22_input_input_shape_ce1 <= ap_const_logic_0;
    conv2d_22_input_input_shape_d0 <= ap_const_lv64_0;
    conv2d_22_input_input_shape_d1 <= ap_const_lv64_0;
    conv2d_22_input_input_shape_we0 <= ap_const_logic_0;
    conv2d_22_input_input_shape_we1 <= ap_const_logic_0;
    dense_23_output_array_address0 <= ap_const_lv14_0;
    dense_23_output_array_address1 <= ap_const_lv14_0;
    dense_23_output_array_ce0 <= ap_const_logic_0;
    dense_23_output_array_ce1 <= ap_const_logic_0;
    dense_23_output_array_d0 <= ap_const_lv32_0;
    dense_23_output_array_d1 <= ap_const_lv32_0;
    dense_23_output_array_we0 <= ap_const_logic_0;
    dense_23_output_array_we1 <= ap_const_logic_0;
    dense_23_output_shape_address0 <= ap_const_lv3_0;
    dense_23_output_shape_address1 <= ap_const_lv3_0;
    dense_23_output_shape_ce0 <= ap_const_logic_0;
    dense_23_output_shape_ce1 <= ap_const_logic_0;
    dense_23_output_shape_d0 <= ap_const_lv64_0;
    dense_23_output_shape_d1 <= ap_const_lv64_0;
    dense_23_output_shape_we0 <= ap_const_logic_0;
    dense_23_output_shape_we1 <= ap_const_logic_0;
end behav;
