// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="navdepp,hls_ip_2018_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=15,HLS_VERSION=2018_2}" *)

module navdepp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2d_22_input_input_array_address0,
        conv2d_22_input_input_array_ce0,
        conv2d_22_input_input_array_we0,
        conv2d_22_input_input_array_d0,
        conv2d_22_input_input_array_q0,
        conv2d_22_input_input_array_address1,
        conv2d_22_input_input_array_ce1,
        conv2d_22_input_input_array_we1,
        conv2d_22_input_input_array_d1,
        conv2d_22_input_input_array_q1,
        conv2d_22_input_input_ndim,
        conv2d_22_input_input_numel,
        conv2d_22_input_input_shape_address0,
        conv2d_22_input_input_shape_ce0,
        conv2d_22_input_input_shape_we0,
        conv2d_22_input_input_shape_d0,
        conv2d_22_input_input_shape_q0,
        conv2d_22_input_input_shape_address1,
        conv2d_22_input_input_shape_ce1,
        conv2d_22_input_input_shape_we1,
        conv2d_22_input_input_shape_d1,
        conv2d_22_input_input_shape_q1,
        dense_23_output_array_address0,
        dense_23_output_array_ce0,
        dense_23_output_array_we0,
        dense_23_output_array_d0,
        dense_23_output_array_q0,
        dense_23_output_array_address1,
        dense_23_output_array_ce1,
        dense_23_output_array_we1,
        dense_23_output_array_d1,
        dense_23_output_array_q1,
        dense_23_output_ndim,
        dense_23_output_numel,
        dense_23_output_shape_address0,
        dense_23_output_shape_ce0,
        dense_23_output_shape_we0,
        dense_23_output_shape_d0,
        dense_23_output_shape_q0,
        dense_23_output_shape_address1,
        dense_23_output_shape_ce1,
        dense_23_output_shape_we1,
        dense_23_output_shape_d1,
        dense_23_output_shape_q1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] conv2d_22_input_input_array_address0;
output   conv2d_22_input_input_array_ce0;
output   conv2d_22_input_input_array_we0;
output  [31:0] conv2d_22_input_input_array_d0;
input  [31:0] conv2d_22_input_input_array_q0;
output  [13:0] conv2d_22_input_input_array_address1;
output   conv2d_22_input_input_array_ce1;
output   conv2d_22_input_input_array_we1;
output  [31:0] conv2d_22_input_input_array_d1;
input  [31:0] conv2d_22_input_input_array_q1;
input  [63:0] conv2d_22_input_input_ndim;
input  [63:0] conv2d_22_input_input_numel;
output  [2:0] conv2d_22_input_input_shape_address0;
output   conv2d_22_input_input_shape_ce0;
output   conv2d_22_input_input_shape_we0;
output  [63:0] conv2d_22_input_input_shape_d0;
input  [63:0] conv2d_22_input_input_shape_q0;
output  [2:0] conv2d_22_input_input_shape_address1;
output   conv2d_22_input_input_shape_ce1;
output   conv2d_22_input_input_shape_we1;
output  [63:0] conv2d_22_input_input_shape_d1;
input  [63:0] conv2d_22_input_input_shape_q1;
output  [13:0] dense_23_output_array_address0;
output   dense_23_output_array_ce0;
output   dense_23_output_array_we0;
output  [31:0] dense_23_output_array_d0;
input  [31:0] dense_23_output_array_q0;
output  [13:0] dense_23_output_array_address1;
output   dense_23_output_array_ce1;
output   dense_23_output_array_we1;
output  [31:0] dense_23_output_array_d1;
input  [31:0] dense_23_output_array_q1;
input  [63:0] dense_23_output_ndim;
input  [63:0] dense_23_output_numel;
output  [2:0] dense_23_output_shape_address0;
output   dense_23_output_shape_ce0;
output   dense_23_output_shape_we0;
output  [63:0] dense_23_output_shape_d0;
input  [63:0] dense_23_output_shape_q0;
output  [2:0] dense_23_output_shape_address1;
output   dense_23_output_shape_ce1;
output   dense_23_output_shape_we1;
output  [63:0] dense_23_output_shape_d1;
input  [63:0] dense_23_output_shape_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_done = 1'b0;

assign ap_ready = 1'b0;

assign conv2d_22_input_input_array_address0 = 14'd0;

assign conv2d_22_input_input_array_address1 = 14'd0;

assign conv2d_22_input_input_array_ce0 = 1'b0;

assign conv2d_22_input_input_array_ce1 = 1'b0;

assign conv2d_22_input_input_array_d0 = 32'd0;

assign conv2d_22_input_input_array_d1 = 32'd0;

assign conv2d_22_input_input_array_we0 = 1'b0;

assign conv2d_22_input_input_array_we1 = 1'b0;

assign conv2d_22_input_input_shape_address0 = 3'd0;

assign conv2d_22_input_input_shape_address1 = 3'd0;

assign conv2d_22_input_input_shape_ce0 = 1'b0;

assign conv2d_22_input_input_shape_ce1 = 1'b0;

assign conv2d_22_input_input_shape_d0 = 64'd0;

assign conv2d_22_input_input_shape_d1 = 64'd0;

assign conv2d_22_input_input_shape_we0 = 1'b0;

assign conv2d_22_input_input_shape_we1 = 1'b0;

assign dense_23_output_array_address0 = 14'd0;

assign dense_23_output_array_address1 = 14'd0;

assign dense_23_output_array_ce0 = 1'b0;

assign dense_23_output_array_ce1 = 1'b0;

assign dense_23_output_array_d0 = 32'd0;

assign dense_23_output_array_d1 = 32'd0;

assign dense_23_output_array_we0 = 1'b0;

assign dense_23_output_array_we1 = 1'b0;

assign dense_23_output_shape_address0 = 3'd0;

assign dense_23_output_shape_address1 = 3'd0;

assign dense_23_output_shape_ce0 = 1'b0;

assign dense_23_output_shape_ce1 = 1'b0;

assign dense_23_output_shape_d0 = 64'd0;

assign dense_23_output_shape_d1 = 64'd0;

assign dense_23_output_shape_we0 = 1'b0;

assign dense_23_output_shape_we1 = 1'b0;

endmodule //navdepp
